### ISSUE TITLE
Password requirements text isn't shown

### ISSUE THREAD

**Issue by Gahata** [itsdouges/armory-ng#15]
As seen in screenshot the password requirement text under password input field on 'join' screen is not shown fully. The not visible part refers to needing to contain one or more uppercase or lowercase characters.
Windows 10, Chrome 52, 1920x1080

![passwordtext-gw2armory](https://cloud.githubusercontent.com/assets/16544306/17665899/d4b10234-62fd-11e6-92ba-76202f049f5a.png)

**Comment by madou** [comment]
Thanks for the heads up, this will be fixed soon.
